version: "3.7"
services:

    graphql:
        container_name: covid-19-graphql-service
        restart: always
        image: covid-19-graphql-service
        build:
            context: ./graphql
        env_file:
            - ./.env
        ports:
            - 5000:5000
        env_file:
            - ./.env
        command:
            [
                "--connection",
                "${DATABASE_URL}",
                "--port",
                "5000",
                "--schema",
                "johns_hopkins,apple_mobility",
                "--enhance-graphiql",
                "--allow-explain",
                "--append-plugins",
                "postgraphile-plugin-connection-filter,@graphile/postgis,postgraphile-plugin-connection-filter-postgis",
            ]
